name: time-slot-availability

services:
  postgresql:
    image: time-slot-availability-db:dev
    container_name: time-slot-availability-db
    build:
      context: ./resources/db
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d coding-challenge -U postgress']
      interval: 3s
      timeout: 5s
      retries: 6
    volumes:
      - time-slot-availability-db-data:/var/lib/postgresql/data
    networks:
      - time-slot-availability

  time-slot-availability-service:
    image: time-slot-availability-service:dev
    container_name: time-slot-availability-service
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    tty: true
    environment:
      NODE_ENV: development
      PORT: 3000
      POSTGRES_DB: coding-challenge
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: mypassword123!
      POSTGRES_PORT: 5432
      POSTGRES_HOST: time-slot-availability-db
      DATABASE_LOGGING: true
    volumes:
      - .:/app
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - time-slot-availability

networks:
  time-slot-availability:
    name: time-slot-availability
    driver: bridge

volumes:
  time-slot-availability-db-data:
    name: time-slot-availability-db-data